apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'nodejs-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['node-redis:8080']
      - job_name: 'redis'
        metrics_path: /metrics
        static_configs:
          - targets: ['redis:6379']
